import {NextResponse} from 'next/server';
import {db,sessionUser,scopePlant,canViewAll} from '@/lib/server';
const cats=['workplace_conditions','compensation_benefits','process_improvement','equipment_tools','work_organization','management_communication','employee_wellbeing','other'];
const statuses=['new','under_review','actioned','closed'];
export async function GET(){
 const me:any=await sessionUser(); if(!me)return NextResponse.json({error:'Unauthorized'},{status:401});
 let q:any=db.from('voe_reports').select('id,reporter_id,plant_id,category,description,status,admin_note,source_eso_report_id,created_at,updated_at,plants(name)').eq('company_id',me.company_id).order('created_at',{ascending:false}); q=scopePlant(q,me); if(!canViewAll(me.role))q=q.eq('reporter_id',me.id);
 const{data,error}=await q;if(error)return NextResponse.json({error:error.message},{status:400});
 const ids=[...new Set((data||[]).map((r:any)=>r.reporter_id))];const{data:emps}=ids.length?await db.from('employees').select('id,employee_no,first_name,last_name,departments(name)').in('id',ids):{data:[] as any[]};const em=new Map((emps||[]).map((e:any)=>[e.id,e]));
 return NextResponse.json({reports:(data||[]).map((r:any)=>{const e:any=em.get(r.reporter_id);return{id:r.id,reporterId:r.reporter_id,reporterName:`${e?.first_name||''} ${e?.last_name||''}`.trim(),employeeId:e?.employee_no||'',department:e?.departments?.name||'',plantId:r.plant_id,plantName:r.plants?.name||'',category:r.category,description:r.description,status:r.status==='under_review'?'Under Review':r.status==='actioned'?'Actioned':r.status==='closed'?'Closed':'New',adminNote:r.admin_note||undefined,sourceEsoReportId:r.source_eso_report_id||undefined,createdAt:r.created_at,updatedAt:r.updated_at}})});
}
export async function POST(req:Request){const me:any=await sessionUser();if(!me)return NextResponse.json({error:'Unauthorized'},{status:401});const b=await req.json();const category=String(b.category||''),description=String(b.description||'').trim();if(!cats.includes(category)||description.length<5)return NextResponse.json({error:'Category and description are required.'},{status:400});const{data,error}=await db.from('voe_reports').insert({company_id:me.company_id,plant_id:me.plant_id,reporter_id:me.id,category,description}).select('id').single();if(error)return NextResponse.json({error:error.message},{status:400});return NextResponse.json({ok:true,id:data.id})}
export async function PATCH(req:Request){const me:any=await sessionUser();if(!me||!canViewAll(me.role))return NextResponse.json({error:'Forbidden'},{status:403});const b=await req.json(),status=String(b.status||'').toLowerCase().replaceAll(' ','_');if(!statuses.includes(status))return NextResponse.json({error:'Invalid status'},{status:400});let q:any=db.from('voe_reports').update({status,admin_note:String(b.adminNote||'').trim()||null,updated_at:new Date().toISOString(),closed_at:status==='closed'?new Date().toISOString():null,closed_by:status==='closed'?me.id:null}).eq('id',String(b.id)).eq('company_id',me.company_id);q=scopePlant(q,me);const{error}=await q;if(error)return NextResponse.json({error:error.message},{status:400});return NextResponse.json({ok:true})}
