import { NextResponse } from 'next/server';import { db,sessionUser,isSuperAdmin } from '@/lib/server';
function cleanCode(v:any){return String(v||'').trim().toUpperCase().replace(/[^A-Z0-9_-]+/g,'-').replace(/^-+|-+$/g,'')}
export async function POST(req:Request){const me:any=await sessionUser();if(!me||!isSuperAdmin(me.role))return NextResponse.json({error:'Only Super Admin can manage plants.'},{status:403});const b=await req.json(),name=String(b.name||'').trim(),code=cleanCode(b.code);if(!name||!code)return NextResponse.json({error:'Plant name and code are required.'},{status:400});const{data:plant,error}=await db.from('plants').insert({company_id:me.company_id,name,code,active:true}).select('id,name,code').single();if(error)return NextResponse.json({error:error.message},{status:400});
 const adminEmployeeId=String(b.adminEmployeeId||'').trim(),adminName=String(b.adminName||'').trim(),adminPassword=String(b.adminPassword||'');
 if(adminEmployeeId||adminName||adminPassword){
  if(!adminEmployeeId||!adminName||adminPassword.length<6){await db.from('plants').delete().eq('id',plant.id).eq('company_id',me.company_id);return NextResponse.json({error:'To create a Plant Admin, full name, Employee ID and a password of at least 6 characters are required.'},{status:400})}
  const parts=adminName.split(/\s+/),first=parts.shift()||'',last=parts.join(' ')||'-';
  const{data:admin,error:adminError}=await db.from('employees').insert({company_id:me.company_id,plant_id:plant.id,employee_no:adminEmployeeId,first_name:first,last_name:last,department_id:null,role:'admin',annual_eso_target:12,active:true,password_hash:null}).select('id').single();
  if(adminError){await db.from('plants').delete().eq('id',plant.id).eq('company_id',me.company_id);return NextResponse.json({error:adminError.message},{status:400})}
  const pw=await db.rpc('admin_set_eso_password',{p_user_id:admin.id,p_new_password:adminPassword});if(pw.error){await db.from('employees').delete().eq('id',admin.id);await db.from('plants').delete().eq('id',plant.id).eq('company_id',me.company_id);return NextResponse.json({error:pw.error.message},{status:400})}
 }
 return NextResponse.json({ok:true,plant});} 
export async function PATCH(req:Request){const me:any=await sessionUser();if(!me||!isSuperAdmin(me.role))return NextResponse.json({error:'Only Super Admin can manage plants.'},{status:403});const b=await req.json(),updates:any={};if(b.name!==undefined)updates.name=String(b.name||'').trim();if(b.code!==undefined)updates.code=cleanCode(b.code);if(b.active!==undefined)updates.active=!!b.active;const{error}=await db.from('plants').update(updates).eq('company_id',me.company_id).eq('id',b.id);if(error)return NextResponse.json({error:error.message},{status:400});return NextResponse.json({ok:true});}
