import { NextResponse } from 'next/server'; import { db,sessionUser,canMaintain,canAdmin,notify,notifyRoles } from '@/lib/server';
async function history(reportId:string,oldStatus:string|null,newStatus:string,meId:string,note?:string){await db.from('eso_status_history').insert({eso_report_id:reportId,old_status:oldStatus,new_status:newStatus,changed_by:meId,note:note||null});}
export async function POST(req:Request){
 const me:any=await sessionUser();if(!me||!canMaintain(me.role))return NextResponse.json({error:'Forbidden'},{status:403});const ct=req.headers.get('content-type')||'';
 if(ct.includes('multipart/form-data')){
   const form=await req.formData();const reportId=String(form.get('reportId')||''),action=String(form.get('action')||''),correctiveAction=String(form.get('correctiveAction')||'').trim();if(action!=='complete')return NextResponse.json({error:'Unknown action'},{status:400});if(!correctiveAction)return NextResponse.json({error:'Corrective action required'},{status:400});
   const {data:t}=await db.from('maintenance_tasks').select('id,assigned_to,status').eq('eso_report_id',reportId).single();if(!canAdmin(me.role)&&t?.assigned_to!==me.id)return NextResponse.json({error:'This task is assigned to another user'},{status:403});const now=new Date().toISOString();
   await db.from('maintenance_tasks').upsert({eso_report_id:reportId,assigned_to:t?.assigned_to||me.id,status:'completed',completed_at:now,completed_by:me.id,completion_note:correctiveAction},{onConflict:'eso_report_id'});await db.from('corrective_actions').insert({eso_report_id:reportId,maintenance_task_id:t?.id||null,action_text:correctiveAction,created_by:me.id});await db.from('eso_reports').update({status:'completed',completed_at:now}).eq('id',reportId);
   const file=form.get('file');if(file instanceof File&&file.size){const ext=file.name.split('.').pop()||'jpg';const path=`completion/${new Date().getFullYear()}/${reportId}/${crypto.randomUUID()}.${ext}`;const buf=Buffer.from(await file.arrayBuffer());const up=await db.storage.from('eso-attachments').upload(path,buf,{contentType:file.type||'image/jpeg'});if(up.error)return NextResponse.json({error:up.error.message},{status:400});await db.from('eso_attachments').insert({eso_report_id:reportId,storage_path:path,file_name:file.name,mime_type:file.type,uploaded_by:me.id,attachment_type:'completion'});}
   await history(reportId,t?.status||null,'completed',me.id,correctiveAction);await notifyRoles(['admin','super_admin','management'],'task_completed','ESO task completed','A maintenance/supervisor task was completed.',reportId);return NextResponse.json({ok:true});
 }
 const {reportId,action,assignedTo}=await req.json();
 if(action==='assign'){
   if(!canAdmin(me.role))return NextResponse.json({error:'Only Admin or Super Admin can assign tasks'},{status:403});const {data:assignee}=await db.from('employees').select('id,role,active').eq('id',assignedTo).single();if(!assignee?.active||!['maintenance','supervisor'].includes(assignee.role))return NextResponse.json({error:'Select an active Maintenance or Supervisor user'},{status:400});
   const {data:r}=await db.from('eso_reports').select('status,report_no').eq('id',reportId).single();const now=new Date().toISOString();const {data:task,error}=await db.from('maintenance_tasks').upsert({eso_report_id:reportId,assigned_to:assignedTo,assigned_by:me.id,status:'assigned',assigned_at:now},{onConflict:'eso_report_id'}).select('id').single();if(error)return NextResponse.json({error:error.message},{status:400});await db.from('eso_reports').update({status:'assigned'}).eq('id',reportId);await history(reportId,r?.status||null,'assigned',me.id,'Task assigned');await notify(assignedTo,'task_assigned','New ESO task assigned',`${r?.report_no||'ESO'} has been assigned to you.`,reportId,task?.id);
 }else if(action==='take'){
   const {data:r}=await db.from('eso_reports').select('status,report_no').eq('id',reportId).single();const now=new Date().toISOString();const {error}=await db.from('maintenance_tasks').upsert({eso_report_id:reportId,assigned_to:me.id,assigned_by:me.id,status:'in_progress',assigned_at:now,started_at:now},{onConflict:'eso_report_id'});if(error)return NextResponse.json({error:error.message},{status:400});await db.from('eso_reports').update({status:'in_progress'}).eq('id',reportId);await history(reportId,r?.status||null,'in_progress',me.id,'Task taken');
 }else if(action==='start'){
   const {data:t}=await db.from('maintenance_tasks').select('assigned_to,status').eq('eso_report_id',reportId).single();if(!canAdmin(me.role)&&t?.assigned_to!==me.id)return NextResponse.json({error:'This task is assigned to another user'},{status:403});await db.from('maintenance_tasks').update({status:'in_progress',started_at:new Date().toISOString()}).eq('eso_report_id',reportId);await db.from('eso_reports').update({status:'in_progress'}).eq('id',reportId);await history(reportId,t?.status||null,'in_progress',me.id,'Task started');await notifyRoles(['admin','super_admin'],'task_started','ESO task started','An assigned ESO task is now in progress.',reportId);
 }else return NextResponse.json({error:'Unknown action'},{status:400});return NextResponse.json({ok:true});
}
