import { NextResponse } from 'next/server'; import { db,sessionUser,canMaintain,canAdmin } from '@/lib/server';
export async function POST(req:Request){const me:any=await sessionUser();if(!me||!canMaintain(me.role))return NextResponse.json({error:'Forbidden'},{status:403});const {reportId,action,correctiveAction,assignedTo}=await req.json();
 if(action==='assign'){
   if(!canAdmin(me.role))return NextResponse.json({error:'Only Admin or Super Admin can assign tasks'},{status:403});
   const {data:assignee}=await db.from('employees').select('id,role,active').eq('id',assignedTo).single();
   if(!assignee?.active||!['maintenance','supervisor'].includes(assignee.role))return NextResponse.json({error:'Select an active Maintenance or Supervisor user'},{status:400});
   const now=new Date().toISOString();const {error}=await db.from('maintenance_tasks').upsert({eso_report_id:reportId,assigned_to:assignedTo,assigned_by:me.id,status:'assigned',assigned_at:now},{onConflict:'eso_report_id'});if(error)return NextResponse.json({error:error.message},{status:400});await db.from('eso_reports').update({status:'assigned'}).eq('id',reportId);
 }else if(action==='take'){
   if(!['maintenance','supervisor'].includes(me.role)&&!canAdmin(me.role))return NextResponse.json({error:'Forbidden'},{status:403});
   const now=new Date().toISOString();const {error}=await db.from('maintenance_tasks').upsert({eso_report_id:reportId,assigned_to:me.id,assigned_by:me.id,status:'in_progress',assigned_at:now,started_at:now},{onConflict:'eso_report_id'});if(error)return NextResponse.json({error:error.message},{status:400});await db.from('eso_reports').update({status:'in_progress'}).eq('id',reportId);
 }else if(action==='start'){
   const {data:t}=await db.from('maintenance_tasks').select('assigned_to').eq('eso_report_id',reportId).single();if(!canAdmin(me.role)&&t?.assigned_to!==me.id)return NextResponse.json({error:'This task is assigned to another user'},{status:403});await db.from('maintenance_tasks').update({status:'in_progress',started_at:new Date().toISOString()}).eq('eso_report_id',reportId);await db.from('eso_reports').update({status:'in_progress'}).eq('id',reportId);
 }else if(action==='complete'){
   if(!String(correctiveAction||'').trim())return NextResponse.json({error:'Corrective action required'},{status:400});const {data:t}=await db.from('maintenance_tasks').select('assigned_to').eq('eso_report_id',reportId).single();if(!canAdmin(me.role)&&t?.assigned_to&&t.assigned_to!==me.id)return NextResponse.json({error:'This task is assigned to another user'},{status:403});const now=new Date().toISOString();await db.from('maintenance_tasks').upsert({eso_report_id:reportId,assigned_to:t?.assigned_to||me.id,status:'completed',completed_at:now},{onConflict:'eso_report_id'});await db.from('corrective_actions').insert({eso_report_id:reportId,action_text:String(correctiveAction).trim(),created_by:me.id});await db.from('eso_reports').update({status:'completed',completed_at:now}).eq('id',reportId);
 }else return NextResponse.json({error:'Unknown action'},{status:400});return NextResponse.json({ok:true});}
