"use client";
import { useEffect,useRef,useState,FormEvent } from 'react';
import { Camera,Upload,X } from 'lucide-react';
import type { ESOReport,Location,User } from '@/types';

async function api(url:string,init?:RequestInit){const r=await fetch(url,init);const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.error||'Request failed');return d;}
async function compressPhoto(file:File){
 if(!file.type.startsWith('image/'))throw new Error('Please select a photo.');
 if(file.size<=400_000&&['image/jpeg','image/png','image/webp'].includes(file.type))return file;
 const url=URL.createObjectURL(file);
 try{
  const img=await new Promise<HTMLImageElement>((resolve,reject)=>{const i=new Image();i.onload=()=>resolve(i);i.onerror=()=>reject(new Error('Use JPG, PNG or WebP photos.'));i.src=url;});
  for(const max of [1600,1200,900]){const scale=Math.min(1,max/Math.max(img.width,img.height));const c=document.createElement('canvas');c.width=Math.max(1,Math.round(img.width*scale));c.height=Math.max(1,Math.round(img.height*scale));c.getContext('2d')!.drawImage(img,0,0,c.width,c.height);
   const blob=await new Promise<Blob|null>(resolve=>c.toBlob(resolve,'image/jpeg',.72));if(blob&&blob.size<=400_000)return new File([blob],file.name.replace(/\.[^.]+$/,'')+'.jpg',{type:'image/jpeg'});
  }throw new Error('Photo is too complex to compress. Choose a smaller image.');
 }finally{URL.revokeObjectURL(url);}
}
type Photo={id:string;name:string;type:string;url?:string};
function PhotoPicker({files,onChange,existing=[],removed=[],onRemove,busy=false,onProcessing}:{files:File[];onChange:(f:File[])=>void;existing?:Photo[];removed?:string[];onRemove?:(ids:string[])=>void;busy?:boolean;onProcessing?:(value:boolean)=>void}){
 const camera=useRef<HTMLInputElement>(null),gallery=useRef<HTMLInputElement>(null),[processing,setProcessing]=useState(false),[error,setError]=useState(''),[previews,setPreviews]=useState<string[]>([]);
 useEffect(()=>{const urls=files.map(f=>URL.createObjectURL(f));setPreviews(urls);return()=>urls.forEach(URL.revokeObjectURL);},[files]);
 const pick=async(e:React.ChangeEvent<HTMLInputElement>)=>{const selected=Array.from(e.target.files||[]);e.target.value='';setError('');if(files.length+existing.length-removed.length+selected.length>8){setError('Maximum 8 photos in this group. Remove a photo before adding another.');return;}setProcessing(true);onProcessing?.(true);try{const next:File[]=[];for(const f of selected)next.push(await compressPhoto(f));onChange([...files,...next]);}catch(e:any){setError(e.message);}finally{setProcessing(false);onProcessing?.(false);}};
 return <div className="photo-picker"><div className="photo-actions"><button type="button" className="photo-choice" disabled={busy||processing} onClick={()=>camera.current?.click()}><Camera size={18}/> Take photo</button><button type="button" className="photo-choice" disabled={busy||processing} onClick={()=>gallery.current?.click()}><Upload size={18}/> Add photos</button><input ref={camera} type="file" className="hidden-file" accept="image/*" capture="environment" onChange={pick}/><input ref={gallery} type="file" className="hidden-file" multiple accept="image/*" onChange={pick}/></div><small>Up to 8 photos per group. Images are compressed before upload.</small>{processing&&<p role="status">Preparing photos… Please wait before saving.</p>}{error&&<p className="form-error">{error}</p>}<div className="eso-photo-grid">{existing.map(p=><div key={p.id} className={removed.includes(p.id)?'photo-removed':''}>{p.url&&<img src={p.url} alt={p.name}/>}<small>{p.name}</small><button type="button" disabled={busy} className="outline-small" onClick={()=>onRemove?.(removed.includes(p.id)?removed.filter(id=>id!==p.id):[...removed,p.id])}>{removed.includes(p.id)?'UNDO REMOVE':'REMOVE'}</button></div>)}{files.map((f,i)=><div key={`${i}-${f.name}`}><img src={previews[i]} alt={f.name}/><small>{f.name}</small><button type="button" className="outline-small" disabled={busy||processing} onClick={()=>onChange(files.filter((_,j)=>j!==i))}>REMOVE</button></div>)}</div></div>;
}
function LocationFields({locations,primary,setPrimary,extra,setExtra,plantId}:{locations:Location[];primary:string;setPrimary:(s:string)=>void;extra:string[];setExtra:(s:string[])=>void;plantId?:string}){
 const plant=plantId||locations.find(l=>l.id===primary)?.plantId;
 const available=locations.filter(l=>(!plantId||l.plantId===plantId)&&(l.active!==false||l.id===primary||extra.includes(l.id)));
 return <><label>Primary location<select aria-label="Primary location" value={primary} onChange={e=>{setPrimary(e.target.value);setExtra(extra.filter(id=>id!==e.target.value&&locations.find(l=>l.id===id)?.plantId===locations.find(l=>l.id===e.target.value)?.plantId));}}><option value="">Select location</option>{available.map(l=><option key={l.id} value={l.id}>{l.plantName?`${l.plantName} • `:''}{l.name}</option>)}</select></label><fieldset className="additional-locations"><legend>Additional locations <small>(optional, same plant)</small></legend>{!primary?<small>Select a primary location first.</small>:available.filter(l=>l.id!==primary&&l.plantId===plant).map(l=><label className="check-row" key={l.id}><input type="checkbox" checked={extra.includes(l.id)} onChange={e=>setExtra(e.target.checked?[...extra,l.id]:extra.filter(id=>id!==l.id))}/><span>{l.name}</span></label>)}</fieldset></>;
}

export function ReportEntry({user,locations,onDone,detail,onCancel}:{user:User;locations:Location[];onDone:()=>Promise<void>;detail?:any;onCancel?:()=>void}){
 const r=detail?.report,[primary,setPrimary]=useState(r?(r.location_id||''):(locations[0]?.id||'')),[extra,setExtra]=useState<string[]>((detail?.additionalLocations||[]).map((l:any)=>l.location_id)),[category,setCategory]=useState(r?.category||'safety'),[urgency,setUrgency]=useState(r?.urgency||'medium'),[description,setDescription]=useState(r?.description||''),[files,setFiles]=useState<File[]>([]),[removed,setRemoved]=useState<string[]>([]),[processing,setProcessing]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState('');
 const submit=async(e:FormEvent)=>{e.preventDefault();if(busy||processing)return;setBusy(true);setError('');try{const f=new FormData();f.set('action',r?'edit':'create');if(r){f.set('reportId',r.id);f.set('version',String(r.revision));}f.set('locationId',primary);f.set('additionalLocations',JSON.stringify(extra));f.set('category',category);f.set('urgency',urgency);f.set('description',description);f.set('removePhotos',JSON.stringify(removed));files.forEach(file=>f.append('files',file));try{await api('/api/reports',{method:r?'PATCH':'POST',body:f});}catch(first:any){if(!r||!String(first.message||'').toLowerCase().includes('changed'))throw first;const latest=await api(`/api/reports/detail?reportId=${encodeURIComponent(r.id)}`);f.set('version',String(latest.report.revision));await api('/api/reports',{method:'PATCH',body:f});}await onDone();}catch(e:any){setError(e.message);}finally{setBusy(false);}};
 return <form className="form-panel eso-edit-form" onSubmit={submit}><h3>{r?'Edit ESO':'Report ESO'}</h3><p>{user.name} • {r?'Changes are recorded in the audit history.':'Environmental & Safety Opportunity'}</p><fieldset disabled={busy}><LocationFields locations={locations} primary={primary} setPrimary={setPrimary} extra={extra} setExtra={setExtra} plantId={r?.plant_id}/><div className="form-grid"><label>Category<select aria-label="Category" value={category} onChange={e=>setCategory(e.target.value)}><option value="safety">Safety</option><option value="environmental">Environmental</option></select></label><label>Importance / Urgency<select aria-label="Importance / Urgency" value={urgency} onChange={e=>setUrgency(e.target.value)}>{['low','medium','high','critical'].map(v=><option key={v} value={v}>{v[0].toUpperCase()+v.slice(1)}</option>)}</select></label></div><label>Description<textarea aria-label="Description" rows={5} required minLength={5} maxLength={10000} value={description} onChange={e=>setDescription(e.target.value)}/></label><h4>Before photos</h4><PhotoPicker files={files} onChange={setFiles} existing={(detail?.photos||[]).filter((p:Photo)=>p.type==='report')} removed={removed} onRemove={setRemoved} busy={busy} onProcessing={setProcessing}/></fieldset>{error&&<div role="alert" className="form-error">{error}</div>}<div className="form-actions">{onCancel&&<button type="button" className="outline-btn" disabled={busy} onClick={onCancel}>Cancel</button>}<button className="primary-btn" disabled={busy}>{busy?'SAVING…':r?'SAVE CHANGES':'SUBMIT ESO'}</button></div></form>;
}
export function CompletionForm({detail,onDone,onCancel}:{detail:any;onDone:()=>Promise<void>;onCancel:()=>void}){
 const editing=['completed','closed'].includes(detail.report.status),[text,setText]=useState(editing?detail.task?.completion_note||'':''),[files,setFiles]=useState<File[]>([]),[removed,setRemoved]=useState<string[]>([]),[processing,setProcessing]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState('');
 const submit=async(e:FormEvent)=>{e.preventDefault();if(busy||processing)return;setBusy(true);setError('');try{const f=new FormData();f.set('action',editing?'edit_completion':'complete');f.set('reportId',detail.report.id);f.set('version',String(detail.report.revision));f.set('correctiveAction',text);f.set('removePhotos',JSON.stringify(removed));files.forEach(file=>f.append('files',file));try{await api('/api/maintenance',{method:'POST',body:f});}catch(first:any){if(!editing||!String(first.message||'').toLowerCase().includes('changed'))throw first;const latest=await api(`/api/reports/detail?reportId=${encodeURIComponent(detail.report.id)}`);f.set('version',String(latest.report.revision));await api('/api/maintenance',{method:'POST',body:f});}await onDone();}catch(e:any){setError(e.message);}finally{setBusy(false);}};
 return <form className="form-panel eso-edit-form" onSubmit={submit}><h3>{editing?'Edit completion':detail.task?.assigned_to?'Complete ESO':'Take & resolve'}</h3><p>{editing?'The original resolver and completion date are preserved.':'Your completion and any self-assignment will be recorded together.'}</p><fieldset disabled={busy}><label>Corrective action<textarea aria-label="Corrective action" rows={5} required maxLength={10000} value={text} onChange={e=>setText(e.target.value)}/></label><h4>After photos</h4><PhotoPicker files={files} onChange={setFiles} existing={detail.photos.filter((p:Photo)=>p.type==='completion')} removed={removed} onRemove={setRemoved} busy={busy} onProcessing={setProcessing}/></fieldset>{error&&<div role="alert" className="form-error">{error}</div>}<div className="form-actions"><button type="button" className="outline-btn" disabled={busy} onClick={onCancel}>Cancel</button><button className="primary-btn" disabled={busy||processing||!text.trim()}>{busy?'SAVING…':editing?'SAVE COMPLETION':'COMPLETE ESO'}</button></div></form>;
}
function AuditChanges({event,locations,users}:{event:any;locations:Location[];users:User[]}){
 const before=event.old_values||{},after=event.new_values||{};
 const labels:Record<string,string>={description:'Description',location_id:'Primary location',urgency:'Importance',category:'Category',status:'Status',assigned_to:'Assigned to',assigned_by:'Assigned by',completion_note:'Corrective action',completed_by:'Completed by',completed_at:'Completion date',additional_locations:'Additional locations',photos:'Photos'};
 const fields=['description','location_id','urgency','category','status'],tasks=['assigned_to','assigned_by','completion_note','completed_by','completed_at'];
 const changes=[...fields.map(k=>({key:k,a:before.report?.[k],b:after.report?.[k]})),...tasks.map(k=>({key:k,a:before.task?.[k],b:after.task?.[k]})),...['additional_locations','photos'].map(k=>({key:k,a:before[k],b:after[k]}))].filter(c=>JSON.stringify(c.a)!==JSON.stringify(c.b));
 const display=(key:string,value:any):string=>{
  if(value==null)return '—';
  if(key==='photos')return value.map((p:any)=>p.file_name||'Photo').join(', ')||'None';
  if(key==='location_id')return locations.find(l=>l.id===value)?.name||'Previous location';
  if(key==='additional_locations')return value.map((id:string)=>locations.find(l=>l.id===id)?.name||'Previous location').join(', ')||'None';
  if(['assigned_to','assigned_by','completed_by'].includes(key))return users.find(u=>u.id===value)?.name||'Previous employee';
  if(key==='completed_at')return new Date(value).toLocaleString();
  return String(value).replaceAll('_',' ');
 };
 return <details><summary>View changes</summary>{changes.map(c=><div className="audit-change" key={c.key}><b>{labels[c.key]}</b><div data-no-translate><del>{display(c.key,c.a)}</del><span> → </span><span>{display(c.key,c.b)}</span></div></div>)}</details>;
}
export function ReportWorkspace({report,currentUser,locations,users,onChanged}:{report:ESOReport;currentUser:User;locations:Location[];users:User[];onChanged:()=>Promise<void>}){
 const [detail,setDetail]=useState<any>(null),[error,setError]=useState(''),[mode,setMode]=useState<'view'|'edit'|'complete'>('view'),[busy,setBusy]=useState(false);
 const load=async()=>{const d=await api(`/api/reports/detail?reportId=${encodeURIComponent(report.id)}`);setDetail(d);return d;};
 useEffect(()=>{let active=true;setDetail(null);setError('');api(`/api/reports/detail?reportId=${encodeURIComponent(report.id)}`).then(d=>{if(active)setDetail(d);}).catch(e=>{if(active)setError(e.message);});return()=>{active=false;};},[report.id,report.revision]);
 const saved=async()=>{setMode('view');await load();await onChanged();};
 const take=async(action='take')=>{if(busy)return;setBusy(true);setError('');try{await api('/api/maintenance',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action,reportId:report.id,version:detail.report.revision})});await saved();}catch(e:any){setError(e.message);}finally{setBusy(false);}};
 if(!detail)return <div className="detail-block">{error?<><p className="form-error">{error}</p><button className="outline-btn" onClick={()=>load().catch(e=>setError(e.message))}>Retry</button></>:<p>Loading photos and activity…</p>}</div>;
 const hasAudit=detail.audit.length>0||detail.legacyHistory.length>0;
 if(mode==='edit') return <section className="eso-workspace">{error&&<p className="form-error">{error}</p>}<ReportEntry key={detail.report.revision} user={currentUser} locations={locations} detail={detail} onDone={saved} onCancel={()=>setMode('view')}/></section>;
 if(mode==='complete') return <section className="eso-workspace">{error&&<p className="form-error">{error}</p>}<CompletionForm key={detail.report.revision} detail={detail} onDone={saved} onCancel={()=>setMode('view')}/></section>;
 return <section className="eso-workspace">{error&&<p className="form-error">{error}</p>}<div className="workflow-actions">{detail.permissions.edit&&<button className="outline-btn" onClick={()=>setMode('edit')}>EDIT ESO</button>}{detail.permissions.take&&<button className="outline-btn" disabled={busy} onClick={()=>take()}>TAKE TASK</button>}{detail.permissions.start&&<button className="outline-btn" disabled={busy} onClick={()=>take('start')}>START TASK</button>}{detail.permissions.complete&&<button className="primary-btn" onClick={()=>setMode('complete')}>{detail.task?.assigned_to?'COMPLETE ESO':'TAKE & RESOLVE'}</button>}{detail.permissions.editCompletion&&<button className="outline-btn" onClick={()=>setMode('complete')}>EDIT COMPLETION</button>}<button className="outline-small" onClick={()=>load().catch(e=>setError(e.message))}>REFRESH DETAIL</button></div>{detail.additionalLocations.length>0&&<div className="detail-block"><span>Additional locations</span><p>{detail.additionalLocations.map((l:any)=>l.locations?.name||l.location_id).join(' • ')}</p></div>}<div className="attachment-grid">{['report','completion','corrective_action'].filter(type=>type!=='corrective_action'||detail.photos.some((p:Photo)=>p.type===type)).map(type=><div key={type}><h4>{type==='report'?'Before photos':type==='completion'?'After photos':'Corrective action photos'}</h4><div className="eso-photo-grid">{detail.photos.filter((p:Photo)=>p.type===type).map((p:Photo)=><a key={p.id} href={p.url} target="_blank" rel="noreferrer">{p.url?<img loading="lazy" src={p.url} alt={p.name}/>:<span>Photo unavailable</span>}<small>{p.name}</small></a>)}</div>{!detail.photos.some((p:Photo)=>p.type===type)&&<small>No photos submitted.</small>}</div>)}</div>{hasAudit&&<div className="eso-audit"><h3>Activity / Audit trail</h3>{detail.audit.map((e:any)=><article key={e.id}><b>{e.action.replaceAll('_',' ')} • {e.employees?`${e.employees.first_name} ${e.employees.last_name}`:e.actor_id}</b><small>{new Date(e.created_at).toLocaleString()}</small><AuditChanges event={e} locations={locations} users={users}/></article>)}<details><summary>Existing status history</summary>{detail.legacyHistory.map((h:any)=><article key={h.id}><b>{h.old_status||'Reported'} → {h.new_status}</b><small>{new Date(h.changed_at).toLocaleString()}</small><p data-no-translate>{h.note}</p></article>)}</details></div>}</section>;
}

export function TaskWorkspace({currentUser,reports,users,onOpen,reload}:{currentUser:User;reports:ESOReport[];users:User[];onOpen:(r:ESOReport)=>void;reload:()=>Promise<void>}){
 const [filter,setFilter]=useState('mine'),[assign,setAssign]=useState<ESOReport|null>(null),[assignee,setAssignee]=useState(''),[due,setDue]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState('');
 const admin=['Admin','Super Admin'].includes(currentUser.role),active=reports.filter(r=>r.status!=='Completed');
 const rows=active.filter(r=>filter==='available'?!r.assignedTo:filter==='mine'?r.assignedTo===currentUser.id:filter==='overdue'?r.overdue:true);
 const assignTask=async(e:FormEvent)=>{e.preventDefault();if(!assign||busy)return;setBusy(true);setError('');try{await api('/api/maintenance',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'assign',reportId:assign.id,version:assign.revision,assignedTo:assignee,dueAt:new Date(due).toISOString()})});setAssign(null);await reload();}catch(e:any){setError(e.message);}finally{setBusy(false);}};
 return <div className="page"><h2>Corrective Action Tasks</h2><p>Open an available ESO to take it or resolve it immediately.</p><div className="task-filters">{[['mine','Assigned to me'],['available','Available to take'],['all','All active'],['overdue','Overdue']].map(([v,label])=><button key={v} className={filter===v?'active':''} onClick={()=>setFilter(v)}>{label}</button>)}</div>{error&&<p className="form-error">{error}</p>}<div className="panel"><div className="task-grid">{rows.map(r=><article className={`task-card ${r.overdue?'task-overdue':''}`} key={r.id}><div className="task-top"><b>{r.esoNo}</b><span>{r.urgency}{r.overdue?' • OVERDUE':''}</span></div><h4>{r.location}</h4><p data-no-translate>{r.description}</p><small>{r.assignedToName?`Assigned: ${r.assignedToName}`:'Unassigned'}</small>{r.dueAt&&<small>Due {new Date(r.dueAt).toLocaleString()}</small>}<div className="workflow-actions"><button className="primary-small" onClick={()=>onOpen(r)}>{!r.assignedTo?'TAKE / RESOLVE':'OPEN / COMPLETE'}</button>{admin&&<button className="outline-small" onClick={()=>{setAssign(r);setAssignee(r.assignedTo||'');setDue('');setError('');}}>{r.assignedTo?'REASSIGN':'ASSIGN'}</button>}</div></article>)}</div>{!rows.length&&<div className="empty">No tasks in this view.</div>}</div>{assign&&<div className="modal-backdrop"><form className="small-modal" onSubmit={assignTask}><h3>Assign {assign.esoNo}</h3><label>Assignee<select required value={assignee} onChange={e=>setAssignee(e.target.value)}><option value="">Select user</option>{users.filter(u=>u.active&&u.plantId===assign.plantId&&['Maintenance','Supervisor','Management'].includes(u.role)).map(u=><option key={u.id} value={u.id}>{u.name} • {u.role}</option>)}</select></label><label>Due date<input required type="datetime-local" value={due} onChange={e=>setDue(e.target.value)}/></label>{error&&<p className="form-error">{error}</p>}<div className="form-actions"><button type="button" className="outline-btn" disabled={busy} onClick={()=>setAssign(null)}>Cancel</button><button className="primary-btn" disabled={busy}>ASSIGN</button></div></form></div>}</div>;
}


