import * as XLSX from 'xlsx';
import { db,sessionUser,canViewAll } from '@/lib/server';
function cap(v:string){return v?v[0].toUpperCase()+v.slice(1).replaceAll('_',' '):''}
export async function GET(req:Request){
 const me:any=await sessionUser();if(!me||!canViewAll(me.role))return new Response('Forbidden',{status:403});
 const url=new URL(req.url),format=(url.searchParams.get('format')||'xlsx').toLowerCase(),status=url.searchParams.get('status'),urgency=url.searchParams.get('urgency'),department=url.searchParams.get('department'),from=url.searchParams.get('from'),to=url.searchParams.get('to');
 let q:any=db.from('eso_reports').select('id,report_no,reported_at,category,description,urgency,status,completed_at,reporter_id,locations(name),maintenance_tasks(assigned_to,status,completed_by,completed_at,completion_note),corrective_actions(action_text,created_at),eso_attachments(storage_path,file_name,attachment_type)').order('reported_at',{ascending:false});
 if(status&&status!=='All'){const map:any={'Open':['open'],'In Progress':['assigned','in_progress','waiting'],'Completed':['completed','closed']};q=q.in('status',map[status]||[status.toLowerCase()])}
 if(urgency&&urgency!=='All')q=q.eq('urgency',urgency.toLowerCase());if(from)q=q.gte('reported_at',from);if(to)q=q.lte('reported_at',to+'T23:59:59.999Z');
 const [{data,error},{data:emps}]=await Promise.all([q,db.from('employees').select('id,employee_no,first_name,last_name,annual_eso_target,active,departments(name)').order('last_name')]);if(error)return new Response(error.message,{status:400});
 const userMap=new Map((emps||[]).map((e:any)=>[e.id,e]));
 let rows=(data||[]).map((r:any)=>{const reporter:any=userMap.get(r.reporter_id);const task=r.maintenance_tasks?.[0];const assignee:any=task?.assigned_to?userMap.get(task.assigned_to):null;const resolver:any=(task?.completed_by||task?.assigned_to)?userMap.get(task?.completed_by||task?.assigned_to):null;const ca=(r.corrective_actions||[]).sort((a:any,b:any)=>String(a.created_at).localeCompare(String(b.created_at))).at(-1);const before=(r.eso_attachments||[]).find((a:any)=>a.attachment_type==='report');const after=[...(r.eso_attachments||[])].reverse().find((a:any)=>a.attachment_type==='completion');return {'ESO ID':r.report_no,'Employee ID':reporter?.employee_no||'','Employee':`${reporter?.first_name||''} ${reporter?.last_name||''}`.trim(),'Department':reporter?.departments?.name||'','Location':r.locations?.name||'','Category':cap(r.category),'Description':r.description,'Urgency':cap(r.urgency),'Status':r.status==='completed'||r.status==='closed'?'Completed':r.status==='assigned'||r.status==='in_progress'||r.status==='waiting'?'In Progress':'Open','Reported At':r.reported_at,'Assigned To ID':assignee?.employee_no||'','Assigned To':`${assignee?.first_name||''} ${assignee?.last_name||''}`.trim(),'Task Status':cap(task?.status||''),'Resolved By ID':resolver?.employee_no||'','Resolved By':`${resolver?.first_name||''} ${resolver?.last_name||''}`.trim(),'Corrective Action':ca?.action_text||task?.completion_note||'','Completed At':r.completed_at||task?.completed_at||'','Before Photo File':before?.file_name||'','Before Photo Storage Path':before?.storage_path||'','After Photo File':after?.file_name||'','After Photo Storage Path':after?.storage_path||''}});
 if(department&&department!=='All')rows=rows.filter((r:any)=>r.Department===department);
 const stamp=new Date().toISOString().slice(0,10);
 if(format==='json')return new Response(JSON.stringify(rows,null,2),{headers:{'Content-Type':'application/json','Content-Disposition':`attachment; filename="ESO_Data_${stamp}.json"`}});
 if(format==='csv'){const ws=XLSX.utils.json_to_sheet(rows);return new Response(XLSX.utils.sheet_to_csv(ws),{headers:{'Content-Type':'text/csv;charset=utf-8','Content-Disposition':`attachment; filename="ESO_Data_${stamp}.csv"`}})}
 const wb=XLSX.utils.book_new();XLSX.utils.book_append_sheet(wb,XLSX.utils.json_to_sheet(rows),'ESO Data');const year=new Date().getFullYear(),yrows=rows.filter((r:any)=>String(r['Reported At']).startsWith(String(year)));XLSX.utils.book_append_sheet(wb,XLSX.utils.aoa_to_sheet([['ESO Management Report',year],['Total ESO',yrows.length],['Open',yrows.filter((r:any)=>r.Status==='Open').length],['In Progress',yrows.filter((r:any)=>r.Status==='In Progress').length],['Completed',yrows.filter((r:any)=>r.Status==='Completed').length],['Critical',yrows.filter((r:any)=>r.Urgency==='Critical').length]]),'Summary');
 const departments=Array.from(new Set(yrows.map((r:any)=>r.Department).filter(Boolean))).map(d=>({Department:d,'ESO YTD':yrows.filter((r:any)=>r.Department===d).length,'Open':yrows.filter((r:any)=>r.Department===d&&r.Status==='Open').length,'In Progress':yrows.filter((r:any)=>r.Department===d&&r.Status==='In Progress').length,'Completed':yrows.filter((r:any)=>r.Department===d&&r.Status==='Completed').length}));XLSX.utils.book_append_sheet(wb,XLSX.utils.json_to_sheet(departments),'Department Summary');
 const empPerf=(emps||[]).filter((e:any)=>e.active).map((e:any)=>{const count=yrows.filter((r:any)=>r['Employee ID']===e.employee_no).length;return {'Employee ID':e.employee_no,'Employee':`${e.first_name} ${e.last_name}`,'Department':e.departments?.name||'','ESO YTD':count,'Annual Target':e.annual_eso_target,'Achievement %':e.annual_eso_target?Math.round(count/e.annual_eso_target*100):100,'Remaining':Math.max(0,e.annual_eso_target-count)}});XLSX.utils.book_append_sheet(wb,XLSX.utils.json_to_sheet(empPerf),'Employee Performance');
 const out=XLSX.write(wb,{type:'buffer',bookType:'xlsx'});return new Response(out,{headers:{'Content-Type':'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet','Content-Disposition':`attachment; filename="ESO_Report_${stamp}.xlsx"`}})
}
